--- @diagnostic disable:undefined-global
add_requires('imgui v1.90-docking', { configs = { glfw = true, vulkan = true } })
add_requires('glfw')
add_requires('glm')
add_requires('stb')
add_requires('spdlog')
add_requires('vulkan-headers')

if is_os('windows') then
    target('Walnut')
    set_languages('c++20')
    set_kind('static')
    add_files('Source/**.cpp', 'Platform/GUI/**.cpp')
    add_includedirs('Source')
    add_includedirs('Platform')
    add_packages('imgui')
    add_packages('glfw')
    add_packages('glm')
    add_packages('stb')
    add_packages('spdlog')
    add_packages('vulkan-headers')
else
    target('Walnut')
    set_languages('c++20')
    set_kind('static')
    add_files('Source/**.cpp', 'Platform/GUI/**.cpp')
    add_defines('GLFW_INCLUDE_NONE')
    add_defines('GLFW_INCLUDE_VULKAN')
    add_includedirs('Source')
    add_includedirs('Platform/GUI')
    add_packages('imgui')
    add_packages('glfw')
    add_packages('glm')
    add_packages('stb')
    add_packages('vulkan-headers')
    add_packages('spdlog')
end
